---
- name: Setup prompting
  hosts: all

  tasks:
    - name: Set up prompt
      template: src=templates/bash-prompt.sh dest=~/.bash-prompt.sh
    - name: Source .bash-prompt.sh in .bashrc
      lineinfile: dest=~/.bashrc line="source ~/.bash-prompt.sh"
