---
- name: Setup prompting
  hosts: all

  tasks:
    - name: Set up prompt
      template: src=templates/.bash-prompt dest=~/.bash-prompt
    - name: Source .bash-prompt in .bashrc
      lineinfile: dest=~/.bashrc line="source ~/.bash-prompt"
